name: Minecraft Purpur Server Test

on:
  workflow_dispatch: # manuell auslösen

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1. Java 21 installieren
      - name: Install Java 21
        run: |
          sudo apt update
          sudo apt install -y openjdk-21-jdk
          java -version

      # 2. Arbeitsverzeichnis erstellen
      - name: Create server directory
        run: mkdir -p $GITHUB_WORKSPACE/minecraft_server

      # 3. Purpur Server herunterladen
      - name: Download Purpur 1.21.4 Build 2416
        run: |
          curl -L -o $GITHUB_WORKSPACE/minecraft_server/purpur.jar \
          https://api.purpurmc.org/v2/purpur/1.21.4/2416/download

      # 4. EULA akzeptieren
      - name: Accept EULA
        run: echo "eula=true" > $GITHUB_WORKSPACE/minecraft_server/eula.txt

      # 5. Server starten (nur für Testzwecke)
      - name: Start Minecraft Server
        run: |
          cd $GITHUB_WORKSPACE/minecraft_server
          java -Xmx2G -Xms1G -jar purpur.jar nogui
