name: Minecraft Purpur Server mit Playit

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - uses: actions/checkout@v5

      # 2. Java 21 installieren
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      # 3. Arbeitsverzeichnis für Minecraft Server erstellen
      - name: Create server directory
        run: mkdir -p $GITHUB_WORKSPACE/minecraft_server

      # 4. Purpur 1.21.4 Build 2416 herunterladen
      - name: Download Purpur Server
        run: |
          curl -L -o $GITHUB_WORKSPACE/minecraft_server/purpur.jar \
          https://api.purpurmc.org/v2/purpur/1.21.4/2416/download

      # 5. EULA akzeptieren
      - name: Accept EULA
        run: echo "eula=true" > $GITHUB_WORKSPACE/minecraft_server/eula.txt

      # 6. Playit.gg installieren
      - name: Install Playit.gg
        run: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install -y playit

      # 7. Playit.gg Agent starten (ohne Token)
      - name: Start Playit Agent
        run: playit &

      # 8. Minecraft Purpur Server starten
      - name: Start Minecraft Server
        run: |
          cd $GITHUB_WORKSPACE/minecraft_server
          java -Xmx2G -Xms1G -jar purpur.jar nogui
