name: Minecraft Purpur Server Repo-Sync Force Direct

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      # 1b. Force-reset auf neuesten Stand
      - name: Reset to latest
        run: |
          git fetch origin main
          git reset --hard origin/main

      # 2. Java 21 installieren
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      # 3. RAM prüfen
      - name: Check available RAM
        run: free -h

      # 4. Minecraft Server starten (max 15 GB RAM) im Hintergrund
      - name: Start Minecraft Server
        run: |
          cd $GITHUB_WORKSPACE/minecraft_server
          java -Xmx15G -Xms1G -jar purpur.jar nogui &
          echo $! > server.pid

      # 5. Kontinuierlich Force Push direkt in minecraft_server/
      - name: Continuous force push Minecraft server
        run: |
          while kill -0 $(cat minecraft_server/server.pid) 2>/dev/null; do
            echo "=== Force Push Loop ==="

            # Git vorbereiten
            cd $GITHUB_WORKSPACE
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            # Alle Dateien aus dem laufenden Server-Ordner hinzufügen, temporäre Dateien ignorieren
            rsync -a --ignore-errors --exclude='*.tmp' --exclude='session.lock' minecraft_server/ minecraft_server/

            # Git commit & Force Push
            git add -A minecraft_server || true
            git commit -m "Force push Minecraft server data $(date)" || echo "No changes to commit"
            git push origin HEAD:main --force || echo "Push failed, ignored"

            # 60 Sekunden warten
            sleep 60
          done
