name: Minecraft Purpur Server mit ngrok

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - uses: actions/checkout@v5

      # 2. Java 21 installieren
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      # 3. Arbeitsverzeichnis für den Server erstellen
      - name: Create server directory
        run: mkdir -p $GITHUB_WORKSPACE/minecraft_server

      # 4. Purpur 1.21.4 Build 2416 herunterladen
      - name: Download Purpur Server
        run: |
          curl -L -o $GITHUB_WORKSPACE/minecraft_server/purpur.jar \
          https://api.purpurmc.org/v2/purpur/1.21.4/2416/download

      # 5. EULA akzeptieren
      - name: Accept EULA
        run: echo "eula=true" > $GITHUB_WORKSPACE/minecraft_server/eula.txt

      # 6. ngrok installieren
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
            sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
            sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

      # 7. ngrok mit hartkodiertem Token konfigurieren
      - name: Authenticate ngrok
        run: ngrok config add-authtoken 32tIlbkpBmAbcBAnhFMXQeyJQZd_5HmmRg8dLwKBgaWRefvTB

      # 8. ngrok TCP Tunnel starten
      - name: Start ngrok tunnel
        run: |
          nohup ngrok tcp 25565 --log=stdout > ngrok.log &
          sleep 5
          echo "Ngrok tunnel URL:"
          grep -o 'tcp://[0-9a-zA-Z\.\-:]*' ngrok.log

      # 9. Minecraft Purpur Server starten
      - name: Start Minecraft Server
        run: |
          cd $GITHUB_WORKSPACE/minecraft_server
          java -Xmx2G -Xms1G -jar purpur.jar nogui
