name: Minecraft Purpur Server mit Playit Plugin, OP und Repo-Sync

on:
  workflow_dispatch:

permissions:
  contents: write   # erlaubt github-actions, ins Repo zu pushen

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken (immer neueste Dateien holen)
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2. Java 21 installieren
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      # 3. RAM-Verfügbarkeit prüfen
      - name: Check available RAM
        run: |
          echo "=== RAM Info ==="
          free -h

      # 4. Minecraft Server starten + Auto-Save-Schleife
      - name: Start server with auto-save loop
        run: |
          cd $GITHUB_WORKSPACE/minecraft_server

          # Server im Hintergrund starten
          java -Xmx15G -Xms1G -jar purpur.jar nogui &
          SERVER_PID=$!

          echo "Minecraft-Server gestartet mit PID $SERVER_PID"

          # Git konfigurieren
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Auto-Save-Schleife
          while kill -0 $SERVER_PID 2>/dev/null; do
            git add .
            git commit -m "Auto-save at $(date)" || true
            git push --force
            echo "Auto-save durchgeführt."
            sleep 60
          done

          echo "Minecraft-Server beendet, Auto-Save-Schleife gestoppt."
