#!/bin/bash
set -e

# -------------------------------
# 1. Java 21 installieren
# -------------------------------
echo "Installing Java 21..."
sudo apt update
sudo apt install -y openjdk-21-jdk curl gnupg

# Prüfen
java -version

# -------------------------------
# 2. Arbeitsverzeichnis für Minecraft Server
# -------------------------------
SERVER_DIR="$HOME/minecraft_server"
mkdir -p "$SERVER_DIR"
cd "$SERVER_DIR"

# -------------------------------
# 3. Purpur 1.21.4 Build 2416 herunterladen
# -------------------------------
echo "Downloading Purpur 1.21.4 Build 2416..."
curl -L -o purpur.jar https://api.purpurmc.org/v2/purpur/1.21.4/2416/download

# -------------------------------
# 4. EULA akzeptieren
# -------------------------------
echo "Accepting EULA..."
echo "eula=true" > eula.txt

# -------------------------------
# 5. Playit.gg installieren
# -------------------------------
echo "Installing Playit.gg..."
curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
sudo apt update
sudo apt install -y playit

# -------------------------------
# 6. Playit starten (erfordert Token)
# -------------------------------
echo "Starting Playit.gg client..."
echo "Please enter your Playit.gg token (get it from https://playit.gg):"
read PLAYIT_TOKEN
playit token $PLAYIT_TOKEN
playit start &  # Startet Playit im Hintergrund

# -------------------------------
# 7. Minecraft Purpur Server starten
# -------------------------------
echo "Starting Minecraft Purpur Server..."
java -Xmx10G -Xms5G -jar purpur.jar nogui
